### ISSUE TITLE
database/main.py error

### ISSUE THREAD

**Issue by jwnigel** [jwnigel/permaculture#7]
Somewhere the genus and species are being split with a tab \t and every plant results in an error. 
I've tried splitting genus and species seperately and then stripping  with .strip() but can't figure it out. 

Running test_plants.txt returns this:

Errors: ['Bunium\tbulbocastanum ', 'Calamintha\tnepeta ', 'Carex\tpensylvanica ', 'Carya\tillinoinensis ', 'Gymnocarpium\tdryopteris ', 'Halesia\ttetraptera ', 'Juglans\tnigra ', 'Juglans\tregia ', 'Malus\tpumila ', 'Malva\talcea ']

**Comment by berteh** [comment]
The tab character (\t) was in the source (.txt) file, likely a settings from the text editor last used to edit that list (or a unhappy copy-paste from excel).

Since it's likely to happen again I added a quick regexp fix to replace all multiple space chars in input document by single space character.

**Comment by jwnigel** [comment]
Yes, I did copy/paste it from excel but viewing the .txt file in vs code it looked like just a space separator. Thanks!

**Comment by jwnigel** [comment]
Can I make you a co owner of the repo so you can close issues and pull?

**Comment by jwnigel** [comment]
> Can I make you a co owner of the repo so you can close issues and pull?

Ah, I see that the answer is no, unless I use an organization account
